server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  tomcat:
    connection-timeout: 60000     # HTTP连接超时：60秒
    keep-alive-timeout: 1800000   # Keep-Alive超时：30分钟

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nepm?useSSL=false&serverTimezone=UTC&allowMultiQueries=true&connectTimeout=60000&socketTimeout=0
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 60000
      idle-timeout: 1800000       # 空闲超时：30分钟
      max-lifetime: 3600000       # 最大生命周期：1小时
      leak-detection-threshold: 300000  # 泄漏检测：5分钟

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  # 移除事务超时限制
  transaction:
    default-timeout: 0  # 0表示无超时限制

mybatis:
  type-aliases-package: com.factcheck.app.entity
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 0  # 移除SQL查询超时限制

logging:
  level:
    com.factcheck.app: DEBUG
    org.springframework: INFO
    com.zaxxer.hikari: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: C:/Users/Cleme/Code/Work/factcheck/logs/factcheck.log

fact-check:
  python:
    script-path: C:/Users/Cleme/Code/Work/factcheck/main.py
  upload:
    dir: C:/Users/Cleme/Code/Work/factcheck/uploads
  server:
    url: http://workspace.featurize.cn:35407
  # 移除或大幅增加超时限制
  timeout:
    max-wait: 0           # 0表示无限等待
    query-wait: 0         # 0表示无限等待
    python-exec: 0        # 0表示无限等待
